# These are default options generated by the zsh when a ~/.zshrc is not found

setopt histignorealldups sharehistory

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
setopt HIST_IGNORE_SPACE # Ignore commands started by space
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS


# Use modern completion system
autoload -Uz compinit
compinit

